PhotogramWeb/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DomainViewModels.ViewModels;
using Services.Services;
using ServicesContracts.Contracts;

namespace PhotogramWeb.Controllers
{
    public class PhotoController : Controller
    {
        //
        // GET: /Photo/
        private readonly IPhotoService photoService = new PhotoService();
        private readonly ITagService tagService = new TagService();

        public ActionResult Index()
        {
            return View(photoService.GetPhotoUrlsForUser(User.Identity.Name));
        }

        [Authorize]
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Create()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Details(Int32 photoId)
        {
            return View(photoService.GetPhotoDetailsById(photoId, User.Identity.Name));
        }


        [HttpPost]
//        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize]
        public ActionResult Create(PhotoAddInfoViewModel photoAddInfoViewModel)
        {
            Int32 photoId;
            var file = HttpContext.Request.Files[0];
            if (file != null)
            {
                photoAddInfoViewModel.OriginalPhoto = file;
                photoAddInfoViewModel.Login = User.Identity.Name;
                var tags =
                    new List<String>(photoAddInfoViewModel.TagsString.ToLower()
                                                          .Split(new string[] {","},
                                                                 StringSplitOptions.RemoveEmptyEntries));
                photoAddInfoViewModel.TagAddViewModels = new Collection<TagAddViewModel>();
                foreach (var tag in tags)
                {
                    photoAddInfoViewModel.TagAddViewModels.Add(new TagAddViewModel(tag));
                }
                photoId = photoService.CreatePhoto(photoAddInfoViewModel);
            }
            else
            {
                return View();
            }
            return RedirectToAction("Details", new {photoId = photoId});
        }

        [Authorize]
        public ActionResult Edit(Int32 id)
        {
            if (ModelState.IsValid)
            {
                var photoUpdateInfoViewModel = photoService.GetPhotoForEdit(id);

                return View(photoUpdateInfoViewModel);
            }
            return RedirectToAction("List");
        }


        [HttpPost]
        [Authorize]
        public ActionResult Edit(PhotoUpdateInfoViewModel photoUpdateInfoViewModel)
        {
            if (ModelState.IsValid)
            {
                photoUpdateInfoViewModel.Login = User.Identity.Name;
                List<String> tags = new List<String>(photoUpdateInfoViewModel.TagsString.ToLower().Split(new string[] { ","}, StringSplitOptions.RemoveEmptyEntries));
                photoUpdateInfoViewModel.TagsViewModels = new Collection<TagSimpleViewModel>();
                foreach (var tag in tags)
                {
                    photoUpdateInfoViewModel.TagsViewModels.Add(new TagSimpleViewModel(tag));
                }
                photoService.UpdatePhoto(photoUpdateInfoViewModel);
            }
            return RedirectToAction("Details", new { photoId = photoUpdateInfoViewModel.Id });
        }

        public ActionResult ShowPhotosByTag(String tagName)
        {
            var photos = tagService.GetPhotosByTag(tagName, User.Identity.Name);
            return View("List", photos.ToList());
        }

        public ActionResult GetAllUserPhotos(String userName)
        {
            var photos = photoService.GetPhotosByUserLogin(userName);
            return View("List", photos.ToList());
        }

        public ActionResult List(List<PhotoCommonInfoViewModel> photoCommonInfoViewModel)
        {
            return View(photoCommonInfoViewModel);
        }

        public ActionResult PhotoSlide(List<PhotoCommonInfoViewModel> photoCommonViewModels)
        {
            var photoSlideShowViewModels = new List<PhotoSlideShowViewModel>();
            foreach (var photoCommonInfoViewModel in photoCommonViewModels)
            {
                photoSlideShowViewModels.Add(new PhotoSlideShowViewModel(photoCommonInfoViewModel));
            }
            return View(photoSlideShowViewModels);
        }

        [Authorize]
        public String SetEffect(string publicId, string effectName, int valueOfEffect)
        {
            if (effectName.Equals("nofilter"))
            {
                return "";
            }
            return photoService.GetUrlPhoto(publicId, effectName, valueOfEffect);
        }

        [Authorize]
        public PartialViewResult LikePhoto(string photoId)
        {
            return PartialView("_PhotoCommonView", photoService.LikePhoto(Int32.Parse(photoId), User.Identity.Name));
        }

        [Authorize]
        public PartialViewResult DislikePhoto(string photoId)
        {
            return PartialView("_PhotoCommonView", photoService.DislikePhoto(Int32.Parse(photoId), User.Identity.Name));
        }

        [Authorize]
        public PartialViewResult LikePhotoDetailed(string photoId)
        {
            var photoCommon = photoService.LikePhoto(Int32.Parse(photoId), User.Identity.Name);
            var photoDetailed = new PhotoDetailedInfoViewModel
                {
                    AmountOfDislikes = photoCommon.AmountOfDislikes,
                    AmountOfLikes = photoCommon.AmountOfLikes,
                    CommonRaiting = photoCommon.CommonRaiting,
                    OwnerLogin = photoCommon.OwnerOfPhotoName,
                    CurrentUserLogin = photoCommon.CurrentUserName,
                    PhotoId = photoCommon.PhotoId,
                    PhotoUrl = photoCommon.PhotoUrl,
                    IsLiked = photoCommon.IsLiked,
                    IsDisliked = photoCommon.IsDisliked
                    
                };
            return PartialView("_LikeBar", photoDetailed );
        }

        [Authorize]
        public PartialViewResult DislikePhotoDetailed(string photoId)
        {
            var photoCommon = photoService.DislikePhoto(Int32.Parse(photoId), User.Identity.Name);
            var photoDetailed = new PhotoDetailedInfoViewModel
            {
                AmountOfDislikes = photoCommon.AmountOfDislikes,
                AmountOfLikes = photoCommon.AmountOfLikes,
                CommonRaiting = photoCommon.CommonRaiting,
                OwnerLogin = photoCommon.OwnerOfPhotoName,
                CurrentUserLogin = photoCommon.CurrentUserName,
                PhotoId = photoCommon.PhotoId,
                PhotoUrl = photoCommon.PhotoUrl,
                IsLiked = photoCommon.IsLiked,
                IsDisliked = photoCommon.IsDisliked
            };
            return PartialView("_LikeBar", photoDetailed);
        }

        [Authorize]
        public ActionResult GetCurrentUserPhotos()
        {
            return View("List", photoService.GetPhotosByUserLogin(User.Identity.Name).ToList());
        }

        public ActionResult AddEffect(string photoId, string publicId, string effectName, Int32 valueOfEffect)
        {

            return View("Details", photoId);
        }

        [Authorize]
        public PartialViewResult ShowUsersPhotoSlideShow()
        {
            return PartialView("_PhotoSlideShow",
                               photoService.GetPhotosByUserLogin(User.Identity.Name)
                                           .OrderByDescending(photo => photo.CommonRaiting).Take(5)
                                           .Select(photo => photo.PhotoUrl));
        }


        public ActionResult GetTheMostPopularPhotos()
        {
            return RedirectToAction("PhotoSlide", photoService.GetTheMostPopularForSlideShow());
        }

        public ActionResult ShowTheMostPopularPhotos()
        {
            return View("List", photoService.GetTheMostPopular());
        }

        public ActionResult DeletePhoto(Int32 photoId)
        {
            if (!photoService.GetPhotoCommonById(photoId, User.Identity.Name).OwnerOfPhotoName.Equals(User.Identity.Name))
            {
                return RedirectToAction("Details", new {photoId = photoId});
            }
            photoService.DeletePhotoById(photoId);
            return RedirectToAction("GetCurrentUserPhotos");
        }
    }
        
}

PhotogramWeb/Controllers/TagController.cs
using System.Linq;
using System.Web.Mvc;
using DomainViewModels.ViewModels;
using Services.Services;
using ServicesContracts.Contracts;

namespace PhotogramWeb.Controllers
{
    public class TagController : Controller
    {
        //
        // GET: /Tag/
        readonly ITagService tagService = new TagService();
        readonly IPhotoService photoService = new PhotoService();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult Create(TagAddViewModel tagAddViewModel)
        {
            tagService.AddTag(tagAddViewModel);
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            return View(tagService.GetAllTags());
        }


        public JsonResult GelAllTags(string term)
        {
            var tags = tagService.FindTagByName(term);
            return Json(tags.Select(tag => tag.Name).ToList());
        }
            
        [HttpGet]
        public PartialViewResult GetTopTags()
        {
            return PartialView("_TopTags");
        }
        
        [HttpPost]
        public JsonResult GetTop5Tags()
        {
            var topTags = tagService.GetTopTags(5).ToList();
            return Json(new {Tags = topTags.Select(tag => tag.Name), Counts = topTags.Select(tag => tag.Count)});
        }
    }
}

PhotogramWeb/Views/Photo/AddEffect.cshtml
@model DomainViewModels.ViewModels.AfterUploadPhotoViewModel

@{
//    ViewBag.Title = Resources.UIStrings.AddEffects;
}

<h2>AddEffect</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="row-fluid">
        <div class="span6">
            @Resources.UIStrings.OriginalPhoto
            <img src="@Html.DisplayFor(model => model.OriginalPhoto.Url)" style="height: 400px;"/>
        </div>
            @Resources.UIStrings.PhotoWithFilter
@*        <div class="span6"><img src="@Html.DisplayFor(model=> model.ModifiedPhoto.Url)" id="modifiedPhoto" style="height: 400px;"/></div>*@
        <div class="span6"><img src="" id="modifiedPhoto" style="height: 400px;"/></div>
@*        @Html.DropDownList("Эффекты", new SelectList(Model.EffectsViewModels , "EffectName" , "EffectShowName"), new {@onchange = "javascript:selectEffect('@Model.PhotoId')", @id="effect"})*@
@*        @Html.DropDownList("Эффекты", new SelectList(Model.EffectsViewModels , "EffectName" , "EffectShowName"), new { @id="effect"})*@
            @Html.DropDownListFor(model => model.EffectsViewModels, new SelectList(Model.EffectsViewModels , "EffectName" , "EffectShowName", new { @onchange="javascript:selectEffect()", @id="effect"}))

            @Html.DropDownList(@Resources.UIStrings.Effects, new SelectList(Model.EffectsViewModels , "EffectName" , "EffectShowName"), new { @onchange="javascript:selectEffect()", @id="effect"})
            @Html.HiddenFor(model => model.PublicId, new {@id = "publicId"})
            
            <div class="trans_row effects_row with_param">
<h3>Look &amp; Feel</h3>
<div class="trans_fields">
<div class="trans_field">
<span class="label">
Effect:
<a class="help_content" title="&lt;span class=&quot;field_name&quot;&gt;Effect&lt;/span&gt;Apply a filter or an effect on an image. The value includes the name of the effect and an additional parameter that controls the behavior of the specific effect.&lt;a href=&quot;/documentation/image_transformations#effect_parameter&quot; data-popup=&quot;true&quot;&gt;See reference&lt;/a&gt;"></a><span class="help">?</span>
</span>
<div class="selector fixedWidth" id="uniform-effects" style="width: 125px;"><span style="-webkit-user-select: none; width: 90px;">Gradient fade</span><select class="effects_field" id="effects" name="effects"><option value="">No effect</option>
        <option value="grayscale">Grayscale</option>
        <option value="blackwhite">Blackwhite</option>
        <option value="sepia">Sepia</option>
        <option value="brightness">Brightness</option>
        <option value="saturation">Saturation</option>
        <option value="hue">Hue</option>
        <option value="oil_paint">Oil paint</option>
        <option value="vignette">Vignette</option>
        <option value="pixelate">Pixelate</option>
        <option value="pixelate_faces">Pixelate faces</option>
        <option value="gradient_fade">Gradient fade</option>
        <option value="blur">Blur</option>
        <option value="improve">Improve</option>
        <option value="tilt_shift">Tilt shift</option>
        <option value="sharpen">Sharpen</option>
        <option value="unsharp_mask">Unsharp mask</option>
        <option value="pixelate_region">Pixelate region</option>
        <option value="red">Red</option>
        <option value="blue">Blue</option>
        <option value="green">Green</option>
        <option value="contrast">Contrast</option>
        <option value="vibrance">Vibrance</option>
        <option value="auto_color">Auto color</option>
        <option value="auto_brightness">Auto brightness</option>
        <option value="auto_contrast">Auto contrast</option>
        <option value="fill_light">Fill light</option>
        <option value="blur_region">Blur region</option>
        <option value="blur_faces">Blur faces</option>
        <option value="make_transparent">Make transparent</option>
        <option value="trim">Trim</option>
        <option value="mask">Mask</option>
        <option value="shadow">Shadow</option>
        <option value="negate">Negate</option>
        <option value="screen">Screen</option>
        <option value="multiply">Multiply</option>
        <option value="colorize">Colorize</option></select></div>
        </div>
        <div class="trans_field effects_param_holder">
        <span class="label">&nbsp;</span>
        <div class="slider effects_param_slider ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" aria-disabled="false"><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 0%;"></a></div>
        <input class="with_slider effects_param_field" id="effects_param" name="effects_param" type="text" value="">
        </div>
        </div>
        </div>
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
    <script>
        function selectEffect() {
            var effect = $("#effect").val();
            var publicId = $("#publicId").val();
            $.ajax({
                url: '@Url.Action("SetEffect", "Photo")',
                        type: 'GET',
                        data: {
                            publicId: publicId,
                            effectName: effect
                        },
                        success: function (result) {
                            $("img#modifiedPhoto").attr("src", result);
                        },
                        error: function (e) { display(e); }
            });
        }
    </script>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhotogramWeb/Views/Photo/Create.cshtml
@model DomainViewModels.ViewModels.PhotoAddInfoViewModel

@{
    ViewBag.Title = @Resources.UIStrings.CreatePhoto;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval") 
    
}
<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("Create", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row">
            <div class="col-lg-6">
                <div class="well ">
                    <fieldset>
                        <div class="form-group" >
                            @Html.Label(@Resources.UIStrings.UploadPhoto, new { @class = "control-label" })
                            <input type="file" name="file" id="file" accept="image/gif, image/jpeg, image/png" class="col-lg-12 form-control" />
                            @Html.LabelFor(m => m.Description, new { @class = "control-label"})
                            @Html.TextAreaFor(model => model.Description, new { @class = "col-lg-12 form-control", @id="description" })
                            @Html.LabelFor(model => model.TagsString, new { @class = "control-label"})
                            @Html.TextBoxFor(model => model.TagsString, new { @id = "tags", @class = "col-lg-12 form-control"})
                        </div>   
                        <div class="form-group">
                            <div class="col-lg-10 col-lg-offset-8">
                                <button type="submit" class="btn btn-info">
                                    @Resources.UIStrings.Save
                                </button>
                            </div>
                        </div>
                        
                    </fieldset>
                </div>
        
            </div>
        </div>
    
    <script>
    tag = [];
    $('#tags').tagit({
        autocomplete: {
            source: function (request, response) {
                $.ajax({
                    type:"POST",
                    url: '@Url.Action("GelAllTags", "Tag")',
                    dataType: "json",
                    data: {
                        term: request.term
                    },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return {
                                label: item,
                                value: item
                            };
                        }));
                    },
                    error: function (xhr, status, error) {
                    }
                });
            }
        },
        minLength: 2
    });
</script>  
}  

PhotogramWeb/Views/Photo/Details.cshtml
@model DomainViewModels.ViewModels.PhotoDetailedInfoViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}  
@{
    <div class="well">
        @if (Request.IsAuthenticated && (Model.OwnerLogin.Equals(User.Identity.Name)))
        {
            <a href="@Url.Action("DeletePhoto", "Photo", new {photoId = Model.PhotoId})"><i class="glyphicon glyphicon-remove pull-right"  style="font-size: 20px; color: #333;"></i></a>
        }
        <div class="row-fluid">
            <div class="span8">
                <img src="@Model.PhotoUrl"/>
                
                <div class="row-fluid" style="padding-top: 5px;">
                    <div id="likeBar">
                        @Html.Partial("_LikeBar", Model)
                    </div>
                    <div class="offset4 span3">
                        <a href="@Url.Action("GetAllUserPhotos", "Photo", new {userName = Model.OwnerLogin})"><span class="label label-primary">@Model.OwnerLogin</span></a>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="alert alert-dismissable">
                    <h3>@Resources.UIStrings.Description</h3>
                    <br/>
                    @Html.DisplayFor(model => model.Description)
                </div>
                <div class="alert alert-dismissable">
                    <h3>@Resources.UIStrings.Tags</h3>
                    <br/>
                    @foreach (var tag in Model.TagSimpleViewModels)
                    {
                        <a href="@Url.Action("ShowPhotosByTag", "Photo", new {tagName = tag.Name})"><span class="label label-success">@tag.Name</span></a>
                    }   
                </div>	
            </div>
        </div>
    
    </div>
}

<script>
        function likePhoto(photoId) {
            $.ajax({
                url: '@Url.Action("LikePhotoDetailed", "Photo")',
            type: 'GET',
            data: { photoId: photoId },
            success: function (data) {
                $("#likeBar").html(data);
            },
            error: function () {
                //   $("#result-list-index").html("An error occurred while trying to retrieve your data.");
            }
        });
    }
</script>
<script>
    function dislikePhoto(photoId) {
        $.ajax({
            url: '@Url.Action("DislikePhotoDetailed", "Photo")',
            type: 'GET',
            data: { photoId: photoId },
            success: function (data) {
                $("#likeBar").html(data);
            },
            error: function () {
                //  $("#result-list-index").html("An error occurred while trying to retrieve your data.");
            }
        });
    }
</script>

PhotogramWeb/Views/Photo/Edit.cshtml
@model DomainViewModels.ViewModels.PhotoUpdateInfoViewModel

@{
    ViewBag.Title = @Resources.UIStrings.EditPhoto;
}

<script src="~/Scripts/claudinary-effect.js"></script>

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

        
    <div class="row">
        <div class="col-lg-5">
            <div class="well ">
                <fieldset>
                    <div class="form-group">
                        @Html.HiddenFor(model => model.Id)
                        
                        @Html.LabelFor(model => model.Description, new { @class = "control-label"})
                        <br/>
                        @Html.EditorFor(model => model.Description, new { @class = "col-lg-10 form-control"})
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                    <div class="form-group"> 
                        @Html.LabelFor(m => m.TagsString, new { @class = "control-label"})
                        @Html.TextBoxFor(model => model.TagsString, new { @id = "tags", @class = "col-lg-10 form-control", @value=Model.TagsString})
                    </div>
                    
                </fieldset>
            </div>
        </div>
        
    </div>
    <div class="row-fluid">
        <div class="span5">
            <h4>@Resources.UIStrings.OriginalPhoto</h4>
            <img src="@Html.DisplayFor(model => model.OriginalPhoto.Url)" style="height: 350px; width: 350px"/>
        </div>
        <div class="span2" style="text-align:center;">
            <h4>@Resources.UIStrings.Effects</h4>
            @Html.DropDownList(@Resources.UIStrings.Effects, new SelectList(Model.EffectsViewModels , "EffectName" , "EffectShowName"), new { @onchange="javascript:selectEffect()", @id="effect"})
            <div style="padding-top: 5px; text-align:center;">
                <input type="button" id="preview" onclick="runPreview()" value="@Resources.UIStrings.Preview" class="btn-danger" style="padding-top: 5px;"/>
            </div>
            <div style="padding-top: 8px">
                <input type="text" disabled="disabled" id="amount" style="border: 0; color: #f6931f; font-weight: bold; margin: auto; width: 45px;" />
            </div>
            <div id="slider-vertical" style="height: 200px; margin: auto;"></div>
        </div>
        <div class="span5">
            <h4>@Resources.UIStrings.PhotoWithFilter</h4>
            @Html.HiddenFor(model => model.OriginalPhoto.PublicId, new {@id = "publicId"})
            @Html.HiddenFor(model => model.ModifiedPhoto, new {@id = "modifiedUrl"})
            <img src="@Html.DisplayFor(model => model.ModifiedPhoto)" id="modifiedPhoto" style="height: 350px; width: 350px;"/>

        </div>
        <br/>
        <br/>
        <p align="center">
            <button type="submit" class="btn-info">@Resources.UIStrings.Save</button>
        </p>
        
 </div>
       
    <script>
        function runPreview() {
            var publicId = $("#publicId").val();
            $.ajax({
                url: '@Url.Action("SetEffect", "Photo")',
                type: 'GET',
                data: {
                    publicId: publicId,
                    effectName: $("#effect").val(),
                    valueOfEffect: $("#amount").val()
                },
                success: function (result) {
                    $("img#modifiedPhoto").attr("src", result);
                    $("#modifiedUrl").val(result);
                },
                error: function (e) { display(e); }
            });
        }
    </script>
    <script>    
        $('#tags').tagit({
            autocomplete: {
                source: function (request, response) {
                    $.ajax({
                        type:"POST",
                        url: '@Url.Action("GelAllTags", "Tag")',
                        dataType: "json",
                        data: {
                            term: request.term
                        },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return {
                                    label: item,
                                    value: item
                                };
                            }));
                        },
                        error: function (xhr, status, error) {
                        }
                    });
                }
            },
            minLength: 2
        });
    </script>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhotogramWeb/Views/Photo/Index.cshtml
@model IEnumerable<DomainViewModels.ViewModels.PhotoCommonInfoViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@if (Model != null)
{
    @Html.Action("PhotoSlide", "Photo", Model);
}
else
{
    <label>No photo</label>
}

PhotogramWeb/Views/Photo/List.cshtml
@model IEnumerable<DomainViewModels.ViewModels.PhotoCommonInfoViewModel>

@{
    ViewBag.Title = @Resources.UIStrings.Photos;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    <h4><a href="#myModal" role="button" class="btn-toolbar" data-toggle="modal">@Resources.UIStrings.StartSlideShow</a></h4>
    <div class="modal " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" align="center">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <p>@Html.Partial("_PhotoSlide", Model)</p>
      </div>
    </div>
    <br/><br/>
    var tiles = Model.Count() / 3 + 1;
    for (var i = 0; i < tiles; i++)
    {
        <div class="row">
            @foreach (var photo in Model.Skip(i * 3).Take(3))
            {
                <div id="@photo.PhotoId" class="span4">
                    @Html.Partial("_PhotoCommonView", photo)
                </div>
            }
        </div>
    }
}

<script>
    function likePhoto(photoId) {
        $.ajax({
            url: '@Url.Action("LikePhoto", "Photo")',
            type: 'GET',
            data: { photoId: photoId },
            success: function (data) {
                $("#" + photoId).html(data);
            },
            error: function () {
                //   $("#result-list-index").html("An error occurred while trying to retrieve your data.");
            }
        });
    }
</script>
<script>
    function dislikePhoto(photoId) {
        $.ajax({
            url: '@Url.Action("DislikePhoto", "Photo")',
            type: 'GET',
            data: { photoId: photoId },
            success: function (data) {
                $("#" + photoId).html(data);
            },
            error: function() {
                //  $("#result-list-index").html("An error occurred while trying to retrieve your data.");
            }
        });
    }
</script>

PhotogramWeb/Views/Photo/PhotoSlide.cshtml
@model IEnumerable<DomainViewModels.ViewModels.PhotoSlideShowViewModel>
<div class="fotorama">
    @foreach (var url in Model)
    {
        <img src="@url.PhotoUrl">
    }
</div>